server.port=${PORT:8000}
server.address=0.0.0.0
spring.application.name=featureflags
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/featureflags_db}
spring.main.banner-mode=off
logging.level.org.springframework=WARN
logging.level.org.mongodb=WARN
featureflags.jwt.secret=${JWT_SECRET:featureflags-secret-jwt-key-2026}
featureflags.jwt.expires-in=${JWT_EXPIRES_IN:24h}
